### ISSUE TITLE
unable to connect to remote client

### ISSUE THREAD

**Issue by fallenczar** [chonjay21/docker-webdav#1]
Hi,
i am trying to connect my synology nas to my webdav server, but am unable to so. looking at the logs, i get the following error

[Tue Dec 08 20:42:08.326635 2020] [auth_digest:error] AH01781: client used wrong authentication scheme `Basic': /webdav/data/

my container is built using the flag 
-e DIGEST_AUTH_REALM=Webdav, i am unure what this value should be to mitigate this problem

**Comment by chonjay21** [comment]
Hi.
First of all, thank you for using my webdav container.

It seems that the client application(program) does not support digest authentication.
you could remove [-e DIGEST_AUTH_REALM=Webdav] environment variable(flag) for using basic authentication.
